### ISSUE TITLE
is_dataclass check in transform() should only match instances not types

### ISSUE THREAD

**Issue by RedBeard0531** [scravy/awesome-pattern-matching#2]
https://github.com/scravy/awesome-pattern-matching/blob/a6dfd4a6fe1dbf8fffd99c4980c47d05d3ca6250/apm/core.py#L220-L225

Normally you can just pass a type to a terse match, but currently it doesn't work if the type is a dataclass because it tries to match against the type as if it were an instance of the dataclass. https://docs.python.org/3/library/dataclasses.html#dataclasses.is_dataclass recommends using `is_dataclass(obj) and not isinstance(obj, type)` to only match instances.

Example showing the bug:

```python
In [1]: from dataclasses import dataclass

In [2]: @dataclass
   ...: class Foo:
   ...:     x: int
   ...:

In [3]: from apm import *

In [4]: match(Foo(1), Foo, 1) # <--- should work but doesn't
---------------------------------------------------------------------------
MatchError                                Traceback (most recent call last)
<ipython-input-4-58e7e898a729> in <module>
----> 1 match(Foo(1), Foo, 1)

~/.local/lib/python3.9/site-packages/apm/match.py in match(value, pattern, multimatch, strict, captureall, *extra)
     83                 return invoke(acc[0], [])
     84             return acc[0]
---> 85         raise MatchError(value)
     86
     87     if isinstance(captureall, dict):

MatchError: Foo(x=1)

In [5]: match(Foo(1), InstanceOf(Foo), 1) # <--- workaround
Out[5]: 1
```

**Comment by scravy** [comment]
Thanks for the report and tracking it down so neatly. Fixed in e920779 and releases as https://github.com/scravy/awesome-pattern-matching/releases/tag/0.21.2
